#!/usr/bin/env python3

# -*- coding: utf-8 -*-

# Copyright (c) 2020-2022 Jared Daniel Carbonell Recomendable.


from getpass import getuser
import os
import sys
import subprocess


# Computer-specific constants
FILE_MANAGER_CMD = 'nautilus'
HOME_DIR = 'home'
USERNAME = getuser()
DROPBOX_DIR = '/{}/{}/Dropbox/'.format(HOME_DIR, USERNAME)
# DROPBOX_DIR = '/{}/{}/Library/CloudStorage/Dropbox/'.format(HOME_DIR, USERNAME)


# File locations
# Structure:
#     'CMD_PARAM': [AUTO_NAV_DEPTH, 'RELATIVE FILE_LOCATION']
NAV_DIRS = {
        'u-admin'        : [3, 'UoA/ADMIN'],
        'u-books'        : [1, 'UoA/BOOKS'],
        'u-clubs'        : [0, 'UoA/CLUBS'],
        'u-competitions' : [2, 'UoA/COMPETITIONS'],
        'u-courses'      : [1, 'UoA/COURSES'],
        'u-extcurr'      : [3, 'UoA/EXTCURR'],
        'u-w281'         : [0, 'UoA/WORK/SOFTENG281 2023'],
        'u-wra'          : [0, 'UoA/WORK/RA 2022'],
        'u-701b'         : [0, 'UoA/BOOKS/2023-S1/SOFTENG701'],
        'u-770b'         : [0, 'UoA/BOOKS/2023-S1/SOFTENG770'],
        'u-700'          : [2, 'UoA/COURSES/2023-S1/SOFTENG700A'],
        'u-701'          : [2, 'UoA/COURSES/2023-S1/SOFTENG701'],
        'u-750'          : [2, 'UoA/COURSES/2023-S1/SOFTENG750'],
        'u-770'          : [2, 'UoA/COURSES/2023-S1/SOFTENG770'],
}


# Utility Functions
def list_dir():
    '''List directories in current working directory, ascending order.'''
    return sorted(os.listdir())

def auto_nav(target_dir, auto_nav_depth):
    '''Navigate to latest folder.'''
    os.chdir(target_dir)
    target_dir += '/'
    while auto_nav_depth > 0:
        target_dir += str(list_dir()[-1]) + '/'
        os.chdir(target_dir)
        auto_nav_depth -= 1
    return target_dir

def parse_dir_path(cmd_param):
    '''Parse absolute path to target directory.'''
    auto_nav_depth, relative_target_dir = NAV_DIRS[cmd_param]
    target_dir = DROPBOX_DIR + relative_target_dir
    return auto_nav(target_dir, auto_nav_depth)

def parse_cmd(dir_path):
    return '{} "{}"'.format(FILE_MANAGER_CMD, dir_path)

def run(cmd):
    '''Send command to shell.'''
    subprocess.Popen(['bash', '-c', cmd])

def form_help_doc():
    '''Return help documenation.'''
    doc = 'Usage: cdl [-p] [options]\n\nOptions:\n'
    for key in NAV_DIRS:
        doc += '  {:10} go to ~/Dropbox/{}\n'.format(key, NAV_DIRS[key][1])
    return doc


def run_cmd(cmd_param, print_only=False):
    dir_path = parse_dir_path(cmd_param)
    if print_only:
        print(dir_path)
        return
    command = parse_cmd(dir_path)
    print('OPENING "{}"'.format(dir_path))
    run(command)


# Main
if __name__ == '__main__':
    if len(sys.argv) == 2:
        cmd_param = sys.argv[1]
        if cmd_param in NAV_DIRS:
            run_cmd(cmd_param)
        elif cmd_param in ('-h', '--help', '-p'):
            print(form_help_doc())
        else:
            print('Argument not supported.')
    elif len(sys.argv) == 3:
        if sys.argv[1] in NAV_DIRS and sys.argv[2] == '-p':
            run_cmd(sys.argv[1], True)
        elif sys.argv[1] == '-p' and sys.argv[2] in NAV_DIRS:
            run_cmd(sys.argv[2], True)
        else:
            print(form_help_doc())
    else:
        print(form_help_doc())
